Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "classe\u0020pour\u0020l\u0027authentification",
            "url": "classes/App-Http-Controllers-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003AafficherFormulaireConnexion\u0028\u0029",
            "name": "afficherFormulaireConnexion",
            "summary": "affiche\u0020le\u0020formulaire\u0020de\u0020connexion",
            "url": "classes/App-Http-Controllers-AuthController.html#method_afficherFormulaireConnexion"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Aconnecter\u0028\u0029",
            "name": "connecter",
            "summary": "permet\u0020de\u0020lancer\u0020une\u0020tentative\u0020de\u0020connexion",
            "url": "classes/App-Http-Controllers-AuthController.html#method_connecter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003AafficherFormulaireInscription\u0028\u0029",
            "name": "afficherFormulaireInscription",
            "summary": "affiche\u0020le\u0020formulaire\u0020d\u0027inscription",
            "url": "classes/App-Http-Controllers-AuthController.html#method_afficherFormulaireInscription"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Ainscrire\u0028\u0029",
            "name": "inscrire",
            "summary": "permet\u0020d\u0027inscrire\u0020un\u0020nouvel\u0020utilisateur",
            "url": "classes/App-Http-Controllers-AuthController.html#method_inscrire"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Adeconnecter\u0028\u0029",
            "name": "deconnecter",
            "summary": "permet\u0020de\u0020se\u0020d\u00E9connecter",
            "url": "classes/App-Http-Controllers-AuthController.html#method_deconnecter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ConnexionDepuisCookies",
            "name": "ConnexionDepuisCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-ConnexionDepuisCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ConnexionDepuisCookies\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Permet\u0020de\u0020connecter\u0020l\u0027utilisateur\u0020depuis\u0020les\u0020cookies\u0020cr\u00E9\u00E9s\u0020lors\u0020de\u0020l\u0027inscription\u0020ou\u0020de\u0020la\u0020connexion.",
            "url": "classes/App-Http-Middleware-ConnexionDepuisCookies.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MessageThrottleMiddleware",
            "name": "MessageThrottleMiddleware",
            "summary": "",
            "url": "classes/App-Http-Middleware-MessageThrottleMiddleware.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MessageThrottleMiddleware\u003A\u003AbuildException\u0028\u0029",
            "name": "buildException",
            "summary": "on\u0020donne\u0020un\u0020message\u0020quand\u0020la\u0020limite\u0020est\u0020d\u00E9pass\u00E9e.",
            "url": "classes/App-Http-Middleware-MessageThrottleMiddleware.html#method_buildException"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur",
            "name": "Utilisateur",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003AgetAuthPassword\u0028\u0029",
            "name": "getAuthPassword",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#method_getAuthPassword"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_hidden"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        }            ]
);
