Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\AccueilController",
            "name": "AccueilController",
            "summary": "AccueilController",
            "url": "classes/App-Http-Controllers-AccueilController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AccueilController\u003A\u003ArecupActus\u0028\u0029",
            "name": "recupActus",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020actualit\u00E9s.",
            "url": "classes/App-Http-Controllers-AccueilController.html#method_recupActus"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AccueilController\u003A\u003ArecupInfo\u0028\u0029",
            "name": "recupInfo",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020informations\u0020sur\u0020le\u0020service.",
            "url": "classes/App-Http-Controllers-AccueilController.html#method_recupInfo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AccueilController\u003A\u003ArecupCommandeEnCours\u0028\u0029",
            "name": "recupCommandeEnCours",
            "summary": "R\u00E9cup\u00E8re\u0020la\u0020commande\u0020en\u0020cours\u0020pour\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-AccueilController.html#method_recupCommandeEnCours"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AccueilController\u003A\u003Aafficher\u0028\u0029",
            "name": "afficher",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027accueil.",
            "url": "classes/App-Http-Controllers-AccueilController.html#method_afficher"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActualitesController",
            "name": "ActualitesController",
            "summary": "ActualitesController",
            "url": "classes/App-Http-Controllers-ActualitesController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActualitesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020des\u0020actualit\u00E9s\u0020et\u0020\u00E9v\u00E9nements.",
            "url": "classes/App-Http-Controllers-ActualitesController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActuController",
            "name": "ActuController",
            "summary": "ActuController",
            "url": "classes/App-Http-Controllers-ActuController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActuController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020des\u0020actualit\u00E9s.",
            "url": "classes/App-Http-Controllers-ActuController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActuController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Stocke\u0020une\u0020nouvelle\u0020actualit\u00E9\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-ActuController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActuController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Met\u0020\u00E0\u0020jour\u0020une\u0020actualit\u00E9\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-ActuController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ActuController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Supprime\u0020une\u0020actualit\u00E9\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-ActuController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffichageCuisineController",
            "name": "AffichageCuisineController",
            "summary": "AffichageCuisineController",
            "url": "classes/App-Http-Controllers-AffichageCuisineController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AffichageCuisineController\u003A\u003Aafficher\u0028\u0029",
            "name": "afficher",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020la\u0020cuisine\u0020avec\u0020les\u0020commandes\u0020en\u0020cours.",
            "url": "classes/App-Http-Controllers-AffichageCuisineController.html#method_afficher"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\genererNumeroCompte\u0028\u0029",
            "name": "genererNumeroCompte",
            "summary": "g\u00E9n\u00E8re\u0020un\u0020num\u00E9ro\u0020de\u0020compte\u0020unique",
            "url": "namespaces/app-http-controllers.html#function_genererNumeroCompte"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController",
            "name": "AuthController",
            "summary": "classe\u0020pour\u0020l\u0027authentification",
            "url": "classes/App-Http-Controllers-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003AafficherFormulaireConnexion\u0028\u0029",
            "name": "afficherFormulaireConnexion",
            "summary": "affiche\u0020le\u0020formulaire\u0020de\u0020connexion",
            "url": "classes/App-Http-Controllers-AuthController.html#method_afficherFormulaireConnexion"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Aconnecter\u0028\u0029",
            "name": "connecter",
            "summary": "permet\u0020de\u0020lancer\u0020une\u0020tentative\u0020de\u0020connexion",
            "url": "classes/App-Http-Controllers-AuthController.html#method_connecter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003AafficherFormulaireInscription\u0028\u0029",
            "name": "afficherFormulaireInscription",
            "summary": "affiche\u0020le\u0020formulaire\u0020d\u0027inscription",
            "url": "classes/App-Http-Controllers-AuthController.html#method_afficherFormulaireInscription"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Ainscrire\u0028\u0029",
            "name": "inscrire",
            "summary": "permet\u0020d\u0027inscrire\u0020un\u0020nouvel\u0020utilisateur",
            "url": "classes/App-Http-Controllers-AuthController.html#method_inscrire"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\AuthController\u003A\u003Adeconnecter\u0028\u0029",
            "name": "deconnecter",
            "summary": "permet\u0020de\u0020se\u0020d\u00E9connecter",
            "url": "classes/App-Http-Controllers-AuthController.html#method_deconnecter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CarteController",
            "name": "CarteController",
            "summary": "CarteController",
            "url": "classes/App-Http-Controllers-CarteController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CarteController\u003A\u003AafficherGestionCarte\u0028\u0029",
            "name": "afficherGestionCarte",
            "summary": "affiche\u0020la\u0020page\u0020de\u0020gestion\u0020de\u0020la\u0020carte",
            "url": "classes/App-Http-Controllers-CarteController.html#method_afficherGestionCarte"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CarteController\u003A\u003Aajouter\u0028\u0029",
            "name": "ajouter",
            "summary": "Ajoute\u0020un\u0020nouvel\u0020\u00E9l\u00E9ment\u0020\u00E0\u0020la\u0020carte",
            "url": "classes/App-Http-Controllers-CarteController.html#method_ajouter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CarteController\u003A\u003Amodifier\u0028\u0029",
            "name": "modifier",
            "summary": "Met\u0020\u00E0\u0020jour\u0020un\u0020\u00E9l\u00E9ment\u0020de\u0020la\u0020carte",
            "url": "classes/App-Http-Controllers-CarteController.html#method_modifier"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CarteController\u003A\u003Asupprimer\u0028\u0029",
            "name": "supprimer",
            "summary": "Supprime\u0020un\u0020\u00E9l\u00E9ment\u0020de\u0020la\u0020carte",
            "url": "classes/App-Http-Controllers-CarteController.html#method_supprimer"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController",
            "name": "CommandeCuisineController",
            "summary": "CommandeCuisineController",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020des\u0020commandes.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetCommandes\u0028\u0029",
            "name": "getCommandes",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020commandes\u0020du\u0020jour.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getCommandes"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetInventaireItems\u0028\u0029",
            "name": "getInventaireItems",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020d\u00E9tails\u0020d\u0027une\u0020commande.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getInventaireItems"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetCommandeDetails\u0028\u0029",
            "name": "getCommandeDetails",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020d\u00E9tails\u0020d\u0027une\u0020commande.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getCommandeDetails"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AmarquerCommandePayee\u0028\u0029",
            "name": "marquerCommandePayee",
            "summary": "Marque\u0020une\u0020commande\u0020comme\u0020pay\u00E9e.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_marquerCommandePayee"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AmarquerCommandePrete\u0028\u0029",
            "name": "marquerCommandePrete",
            "summary": "Marque\u0020une\u0020commande\u0020comme\u0020pr\u00EAte.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_marquerCommandePrete"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AmarquerCommandeServie\u0028\u0029",
            "name": "marquerCommandeServie",
            "summary": "Marque\u0020une\u0020commande\u0020comme\u0020servie.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_marquerCommandeServie"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AmodifierCommande\u0028\u0029",
            "name": "modifierCommande",
            "summary": "Modifie\u0020une\u0020commande.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_modifierCommande"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AannulerCommande\u0028\u0029",
            "name": "annulerCommande",
            "summary": "Annule\u0020une\u0020commande.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_annulerCommande"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetTestCommande\u0028\u0029",
            "name": "getTestCommande",
            "summary": "R\u00E9cup\u00E8re\u0020la\u0020commande\u0020de\u0020test.",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getTestCommande"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetEtatText\u0028\u0029",
            "name": "getEtatText",
            "summary": "",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getEtatText"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeCuisineController\u003A\u003AgetTypeText\u0028\u0029",
            "name": "getTypeText",
            "summary": "",
            "url": "classes/App-Http-Controllers-CommandeCuisineController.html#method_getTypeText"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeUtilisateurController",
            "name": "CommandeUtilisateurController",
            "summary": "CommandeUtilisateurController",
            "url": "classes/App-Http-Controllers-CommandeUtilisateurController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeUtilisateurController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020commande.",
            "url": "classes/App-Http-Controllers-CommandeUtilisateurController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CommandeUtilisateurController\u003A\u003AvaliderCommande\u0028\u0029",
            "name": "validerCommande",
            "summary": "Valide\u0020la\u0020commande\u0020de\u0020l\u0027utilisateur,\u0020l\u0027ajoute\u0020\u00E0\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-CommandeUtilisateurController.html#method_validerCommande"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompteController",
            "name": "CompteController",
            "summary": "CompteController",
            "url": "classes/App-Http-Controllers-CompteController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompteController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Affiche\u0020la\u0020page\u0020du\u0020compte\u0020utilisateur.",
            "url": "classes/App-Http-Controllers-CompteController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompteController\u003A\u003AlostPassword\u0028\u0029",
            "name": "lostPassword",
            "summary": "Modifie\u0020le\u0020mot\u0020de\u0020passe\u0020de\u0020l\u0027utilisateur\u0020s\u0027il\u0020est\u0020oubli\u00E9.",
            "url": "classes/App-Http-Controllers-CompteController.html#method_lostPassword"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompteController\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "R\u00E9initialise\u0020le\u0020mot\u0020de\u0020passe\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Http-Controllers-CompteController.html#method_resetPassword"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GestionComptesController",
            "name": "GestionComptesController",
            "summary": "CarteController",
            "url": "classes/App-Http-Controllers-GestionComptesController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GestionComptesController\u003A\u003AafficherComptes\u0028\u0029",
            "name": "afficherComptes",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020des\u0020comptes.",
            "url": "classes/App-Http-Controllers-GestionComptesController.html#method_afficherComptes"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GestionComptesController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Met\u0020\u00E0\u0020jour\u0020un\u0020utilisateur\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-GestionComptesController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GestionStocksController",
            "name": "GestionStocksController",
            "summary": "GestionStocksController",
            "url": "classes/App-Http-Controllers-GestionStocksController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\GestionStocksController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020des\u0020stocks.",
            "url": "classes/App-Http-Controllers-GestionStocksController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\IngredientController",
            "name": "IngredientController",
            "summary": "IngredientController",
            "url": "classes/App-Http-Controllers-IngredientController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\IngredientController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020des\u0020ingr\u00E9dients.",
            "url": "classes/App-Http-Controllers-IngredientController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\IngredientController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Ajout\u0020un\u0020nouvel\u0020ingr\u00E9dient\u0020\u00E0\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-IngredientController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\IngredientController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Modifie\u0020un\u0020ingr\u00E9dient\u0020existant.",
            "url": "classes/App-Http-Controllers-IngredientController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\IngredientController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Supprime\u0020un\u0020ingr\u00E9dient\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-IngredientController.html#method_delete"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParametresController",
            "name": "ParametresController",
            "summary": "ParametresController",
            "url": "classes/App-Http-Controllers-ParametresController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParametresController\u003A\u003AafficherParametres\u0028\u0029",
            "name": "afficherParametres",
            "summary": "Affiche\u0020la\u0020page\u0020des\u0020param\u00E8tres\u0020du\u0020site.",
            "url": "classes/App-Http-Controllers-ParametresController.html#method_afficherParametres"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParametresController\u003A\u003AmajTitre\u0028\u0029",
            "name": "majTitre",
            "summary": "Met\u0020\u00E0\u0020jour\u0020le\u0020titre\u0020du\u0020site.",
            "url": "classes/App-Http-Controllers-ParametresController.html#method_majTitre"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ParametresController\u003A\u003AmajModeService\u0028\u0029",
            "name": "majModeService",
            "summary": "Met\u0020\u00E0\u0020jour\u0020les\u0020\u00E9tats\u0020du\u0020site.",
            "url": "classes/App-Http-Controllers-ParametresController.html#method_majModeService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController",
            "name": "PlanningController",
            "summary": "Classe\u0020de\u0020gestion\/affichage\u0020du\u0020planning",
            "url": "classes/App-Http-Controllers-PlanningController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Aafficher\u0028\u0029",
            "name": "afficher",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020gestion\u0020du\u0020planning",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_afficher"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Adonnees\u0028\u0029",
            "name": "donnees",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020donn\u00E9es\u0020du\u0020planning\u0020pour\u0020une\u0020date\u0020donn\u00E9e",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_donnees"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Asupprimer\u0028\u0029",
            "name": "supprimer",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020donn\u00E9es\u0020du\u0020planning\u0020pour\u0020une\u0020date\u0020donn\u00E9e",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_supprimer"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PlanningController\u003A\u003Aajouter\u0028\u0029",
            "name": "ajouter",
            "summary": "Ajoute\u0020une\u0020inscription\u0020au\u0020planning",
            "url": "classes/App-Http-Controllers-PlanningController.html#method_ajouter"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PriseCommandeController",
            "name": "PriseCommandeController",
            "summary": "PriseCommandeController",
            "url": "classes/App-Http-Controllers-PriseCommandeController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\PriseCommandeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020prise\u0020de\u0020commande.",
            "url": "classes/App-Http-Controllers-PriseCommandeController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleSecuriteController",
            "name": "SalleSecuriteController",
            "summary": "SalleSecuriteController",
            "url": "classes/App-Http-Controllers-SalleSecuriteController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleSecuriteController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020la\u0020salle\u0020de\u0020s\u00E9curit\u00E9.",
            "url": "classes/App-Http-Controllers-SalleSecuriteController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleSecuriteController\u003A\u003AajouterReleveFrigo\u0028\u0029",
            "name": "ajouterReleveFrigo",
            "summary": "Enregistre\u0020un\u0020relev\u00E9\u0020de\u0020temp\u00E9rature\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-SalleSecuriteController.html#method_ajouterReleveFrigo"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\SalleSecuriteController\u003A\u003AajouterNettoyage\u0028\u0029",
            "name": "ajouterNettoyage",
            "summary": "Enregistre\u0020un\u0020relev\u00E9\u0020de\u0020nettoyage\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Controllers-SalleSecuriteController.html#method_ajouterNettoyage"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TresorerieController",
            "name": "TresorerieController",
            "summary": "TresorerieController",
            "url": "classes/App-Http-Controllers-TresorerieController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TresorerieController\u003A\u003AobtenirSoldeTotalComptes\u0028\u0029",
            "name": "obtenirSoldeTotalComptes",
            "summary": "R\u00E9cup\u00E8re\u0020le\u0020solde\u0020total\u0020de\u0020tous\u0020les\u0020comptes\u0020utilisateurs.",
            "url": "classes/App-Http-Controllers-TresorerieController.html#method_obtenirSoldeTotalComptes"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TresorerieController\u003A\u003AobtenirSoldeCaisse\u0028\u0029",
            "name": "obtenirSoldeCaisse",
            "summary": "R\u00E9cup\u00E8re\u0020le\u0020solde\u0020de\u0020la\u0020caisse.",
            "url": "classes/App-Http-Controllers-TresorerieController.html#method_obtenirSoldeCaisse"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TresorerieController\u003A\u003AobtenirStatistiquesComptes\u0028\u0029",
            "name": "obtenirStatistiquesComptes",
            "summary": "R\u00E9cup\u00E8re\u0020les\u0020statistiques\u0020des\u0020comptes\u0020utilisateurs.",
            "url": "classes/App-Http-Controllers-TresorerieController.html#method_obtenirStatistiquesComptes"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\TresorerieController\u003A\u003Aafficher\u0028\u0029",
            "name": "afficher",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020la\u0020tr\u00E9sorerie.",
            "url": "classes/App-Http-Controllers-TresorerieController.html#method_afficher"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ConnexionDepuisCookies",
            "name": "ConnexionDepuisCookies",
            "summary": "ConnexionDepuisCookies",
            "url": "classes/App-Http-Middleware-ConnexionDepuisCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ConnexionDepuisCookies\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Permet\u0020de\u0020connecter\u0020l\u0027utilisateur\u0020depuis\u0020les\u0020cookies\u0020cr\u00E9\u00E9s\u0020lors\u0020de\u0020l\u0027inscription\u0020ou\u0020de\u0020la\u0020connexion.",
            "url": "classes/App-Http-Middleware-ConnexionDepuisCookies.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MessageThrottleMiddleware",
            "name": "MessageThrottleMiddleware",
            "summary": "MessageThrottleMiddleware",
            "url": "classes/App-Http-Middleware-MessageThrottleMiddleware.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MessageThrottleMiddleware\u003A\u003AbuildException\u0028\u0029",
            "name": "buildException",
            "summary": "on\u0020donne\u0020un\u0020message\u0020quand\u0020la\u0020limite\u0020est\u0020d\u00E9pass\u00E9e.",
            "url": "classes/App-Http-Middleware-MessageThrottleMiddleware.html#method_buildException"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RecupererDonneesParametres",
            "name": "RecupererDonneesParametres",
            "summary": "RecupererDonneesParametres",
            "url": "classes/App-Http-Middleware-RecupererDonneesParametres.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RecupererDonneesParametres\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020les\u0020donn\u00E9es\u0020des\u0020param\u00E8tres\u0020depuis\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Middleware-RecupererDonneesParametres.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RecupererDonneesUtilisateur",
            "name": "RecupererDonneesUtilisateur",
            "summary": "RecupererDonneesUtilisateur",
            "url": "classes/App-Http-Middleware-RecupererDonneesUtilisateur.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RecupererDonneesUtilisateur\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Permet\u0020de\u0020r\u00E9cup\u00E9rer\u0020les\u0020donn\u00E9es\u0020de\u0020l\u0027utilisateur\u0020depuis\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Http-Middleware-RecupererDonneesUtilisateur.html#method_handle"
        },                {
            "fqsen": "\\App\\Models\\Actu",
            "name": "Actu",
            "summary": "Actu",
            "url": "classes/App-Models-Actu.html"
        },                {
            "fqsen": "\\App\\Models\\Actu\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Actu.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Actu\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Actu.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Actu\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Actu.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Actu\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Actu.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Actus",
            "name": "Actus",
            "summary": "Actus",
            "url": "classes/App-Models-Actus.html"
        },                {
            "fqsen": "\\App\\Models\\Actus\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Actus.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Actus\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Actus.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Actus\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Actus.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Actus\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Actus.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Carte",
            "name": "Carte",
            "summary": "Carte",
            "url": "classes/App-Models-Carte.html"
        },                {
            "fqsen": "\\App\\Models\\Carte\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Carte.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Carte\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Carte.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Carte\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Carte.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Carte\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Carte.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Event",
            "name": "Event",
            "summary": "Carte",
            "url": "classes/App-Models-Event.html"
        },                {
            "fqsen": "\\App\\Models\\Event\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Event.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Event\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Event.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Event\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Event.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Event\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Event.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Ingredient",
            "name": "Ingredient",
            "summary": "Carte",
            "url": "classes/App-Models-Ingredient.html"
        },                {
            "fqsen": "\\App\\Models\\Ingredient\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Ingredient.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Ingredient\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Ingredient.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Ingredient\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Ingredient.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Ingredient\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Ingredient.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeCarte",
            "name": "PriseCommandeCarte",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeCarte.html"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeCarte\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeCarte.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeCarte\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeCarte.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeCarte\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeCarte.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeInventaire",
            "name": "PriseCommandeInventaire",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeInventaire.html"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeInventaire\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeInventaire.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeInventaire\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeInventaire.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\PriseCommandeInventaire\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-PriseCommandeInventaire.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Stock",
            "name": "Stock",
            "summary": "",
            "url": "classes/App-Models-Stock.html"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur",
            "name": "Utilisateur",
            "summary": "Utilisateur",
            "url": "classes/App-Models-Utilisateur.html"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003AgetAuthPassword\u0028\u0029",
            "name": "getAuthPassword",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#method_getAuthPassword"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Utilisateur\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Utilisateur.html#property_fillable"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        }            ]
);
