name: Deploiement SFTP

on:
  push:
    branches: [ deployment ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: 📂 Synchronisation fichiers
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        protocol: ftps
        local-dir: ./ # dossier local
        server-dir: /www/ # dossier sur le serveur
        exclude: vendor/**