on:
  push:
    branches:
      - deploiement
name: 🖥️ Déploiement
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 📢 Début du déploiement
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "🚀 Déploiement lancé sur la branche `deploiement`."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: ⚡ FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          exclude: |
            **/vendor/**
            **/dev/**
            **/documentation/**
            .env
            .env.example
            artisan
            .gitignore
            .gitattributes
            .editorconfig
            .prettierrc
            jsdoc.json
            nodemon.json
            package.json
            package-lock.json
            phpdoc.dist.xml
            phpDocumentor.phar
            README.md
            tailwind.config.js
            .git/**
          local-dir: ./
          server-dir: www/

      - name: ✅ Fin du déploiement
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Déploiement terminé avec succès ! 🎉"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: ❌ Échec du déploiement
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "❌ Échec du déploiement sur la branche `deploiement`."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}