name: Déploiement FTP

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Envoyer les fichiers via FTP
        run: |
          lftp -e "
          set ftp:ssl-allow yes;
          open -u $SFTP_USER,$SFTP_PASSWORD ftp://$SFTP_SERVER;
          mirror --reverse --delete \
                 --exclude vendor/ \
                 --exclude .git/ \
                 ./ /www/
          bye
          "
        env:
          FTP_SERVER: ${{ secrets.SFTP_SERVER }}
          FTP_USER: ${{ secrets.SFTP_USER }}
          FTP_PASS: ${{ secrets.SFTP_PASSWORD }}