on:
  push:
    branches:
      - deployment
name: 🖥️ Déploiement
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: ⚡ FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          exclude: |
            **/vendor/**
            .env
            .env.example
            artisan
            .gitignore
            .gitattributes
            .editorconfig
            nodemon.json
            package.json
            package-lock.json
            README.md
            tailwind.config.js
          local-dir: ./
          server-dir: www/